- app/controllers/bookings_controller.rb
- app/models/booking.rb
- app/models/user.rb
- config/routes.rb
- db/migrate/20201116150648_create_bookings.rb
- db/schema.rb
- test/controllers/bookings_controller_test.rb
- test/models/booking_test.rb
> add booking model

- app/models/availability.rb
- config/routes.rb
- db/migrate/20201116154555_create_availabilities.rb
- db/schema.rb
- test/models/availability_test.rb
> add table availabilities

- app/models/user.rb
- db/migrate/20201116173158_add_column_booked_to_user.rb
- db/migrate/20201116173334_change_default_boolean_column_booked_to_user.rb
- db/migrate/20201116173419_remove_column_default_to_user.rb
- db/migrate/20201116202854_add_booked_column_to_users.rb
- db/schema.rb
…that had a broken migration due to invalid terminal command. The migrations have been deleted and I added another one to create a new column to the users table corresponding to booked as a boolean, default set to false.
> Fixes the user model 

- app/models/availability.rb
- app/models/booking.rb
- app/models/user.rb
Fixes the `belongs_to` associations for Booking and Availability models, as well as the validations for the user model.
> Fixes the models 

- app/controllers/availabilities_controller.rb
> add check access

- app/controllers/application_controller.rb
- app/controllers/pages_controller.rb
- app/models/user.rb
- app/views/devise/registrations/edit.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/profile.html.erb
> User path 2

- app/controllers/application_controller.rb
- app/controllers/cookers_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/users/confirmations_controller.rb
- app/controllers/users/omniauth_callbacks_controller.rb
- app/controllers/users/passwords_controller.rb
- app/controllers/users/registrations_controller.rb
- app/controllers/users/sessions_controller.rb
- app/controllers/users/unlocks_controller.rb
- app/views/devise/registrations/new.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/pages/profile.html.erb
- config/routes.rb
- test/controllers/cookers_controller_test.rb
This adds the redirection, but breaks the update of profile. I am going to fix this right after, but you guys can have the home page and profile page.
> User path 3

- app/controllers/cookers_controller.rb
- app/views/cookers/index.html.erb
- app/views/cookers/show.html.erb
- app/views/pages/profile.html.erb
- config/routes.rb
...sorry pour le code dans la même branch... -_-
> Branch de lextrem session controller

- app/assets/stylesheets/application.scss
- app/controllers/availabilities_controller.rb
- app/javascript/packs/application.js
- app/views/availabilities/index.html.erb
- app/views/pages/profile.html.erb
- config/routes.rb
- package.json
- yarn.lock
> add destroy

- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/layouts/application.html.erb
Just to match the styling I did yesterday on the edit form.
If you're happy with the design, then it's done.
> Styling of the log-in & sign-up forms

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/layouts/application.html.erb
> fixed homepage footer

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_index.scss
- app/views/availabilities/index.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/profile.html.erb
> card on profile

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_modal.scss
- app/javascript/packs/application.js
- app/javascript/pluggins/refresh.js
- app/views/cookers/show.html.erb
- db/schema.rb
Some changes to have to colors on the modal that matches with the website pattern
> Frontend 1

- app/assets/stylesheets/components/_card.scss
- app/views/cookers/index.html.erb
- app/views/cookers/show.html.erb
add card for cookers index and cooker show
> add profile card on cookers index and cooker show

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_navbar.scss
- app/views/components/_navbar.html.erb
- app/views/layouts/application.html.erb
> Responsivecomp

- app/assets/stylesheets/availabilities/_home.scss
- app/views/availabilities/new.html.erb
Find A solution to have availabilities new center. WIP
> Availabilities res

- app/assets/stylesheets/pages/_home.scss
- app/views/layouts/application.html.erb
> fixing the footer

- app/controllers/bookings_controller.rb
- app/controllers/cookers_controller.rb
- app/controllers/pages_controller.rb
- app/models/booking.rb
- app/views/bookings/show.html.erb
- app/views/chatrooms/show.html.erb
- app/views/cookers/show.html.erb
- app/views/pages/profile.html.erb
- config/routes.rb
> changed routes, changed booking view

- db/schema.rb
- db/seeds.rb
> schema + seed

- app/views/pages/profile.html.erb
changing name of cooker on profile/message page
> changing name of cooker on profile/message page

- app/views/chatrooms/show.html.erb
> add number of meals and date in the header

- app/assets/stylesheets/components/_form.scss
- app/controllers/cookers_controller.rb
- app/views/chatrooms/show.html.erb
- app/views/cookers/show.html.erb
- app/views/messages/_message.html.erb
- app/views/pages/profile.html.erb
> Front end fix

- app/controllers/application_controller.rb
adding favorite_utensil to application_controller
> adding favorite_utensil to application_controller

- app/assets/stylesheets/components/_button.scss
- app/views/cookers/show.html.erb
- app/views/pages/profile.html.erb
This commit fixes the display on the cook show, where you click one button to display the corresponding section.
> Fix display sections cook show
